# Generated by Django 3.1.3 on 2020-11-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnig_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
    ]
