# Generated by Django 3.1.3 on 2020-11-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnig_logs', '0003_auto_20201109_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
